export const MovieListActions = {
    FETCH_MOVIES : "FETCH_MOVIES",
    FETCH_MOVIES_SUCCESS:"FETCH_MOVIES_SUCCESS",
    FETCH_MOVIES_FAIL:"FETCH_MOVIES_FAIL"
}

export const GenreActions = {
    FETCH_GENRE : "FETCH_GENRE",
    FETCH_GENRE_SUCCESS:"FETCH_GENRE_SUCCESS",
    FETCH_GENRE_FAIL:"FETCH_GENRE_FAIL"
}